# Generated by Django 6.1 on 2026-08-21 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bairro', models.CharField(max_length=120)),
                ('rua', models.CharField(max_length=160)),
                ('numero', models.CharField(max_length=20)),
                ('cidade', models.CharField(max_length=120)),
                ('estado', models.CharField(max_length=2)),
                ('ativo', models.BooleanField(default=True)),
                ('nome_completo', models.CharField(max_length=200)),
                ('empresa', models.CharField(max_length=200)),
                ('cargo', models.CharField(max_length=120)),
                ('cnpj', models.CharField(max_length=14, unique=True)),
                ('contato_anterior', models.DateField(blank=True, null=True)),
                ('descricao_pedido', models.TextField()),
                ('telefone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bairro', models.CharField(max_length=120)),
                ('rua', models.CharField(max_length=160)),
                ('numero', models.CharField(max_length=20)),
                ('cidade', models.CharField(max_length=120)),
                ('estado', models.CharField(max_length=2)),
                ('ativo', models.BooleanField(default=True)),
                ('nome_completo', models.CharField(max_length=200)),
                ('funcao', models.CharField(max_length=120)),
                ('estado_civil', models.CharField(max_length=40)),
                ('data_admissao', models.DateField()),
                ('data_nascimento', models.DateField()),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('celular', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name': 'Funcionário',
                'verbose_name_plural': 'Funcionários',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('descricao', models.CharField(max_length=250)),
                ('quantidade_disponivel', models.IntegerField(default=0)),
                ('fabricante', models.CharField(max_length=120)),
                ('data_aquisicao', models.DateField()),
                ('data_vencimento', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('data', models.DateField()),
                ('descricao', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada'), ('saida', 'Saída')], max_length=12)),
                ('categoria', models.CharField(choices=[('salarios', 'Salários'), ('materiais', 'Materiais'), ('aluguel', 'Aluguel'), ('outros', 'Outros')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Falta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('presente', models.BooleanField(default=False)),
                ('motivo', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('justificada', 'Justificada'), ('nao_justificada', 'Não justificada')], default='nao_justificada', max_length=24)),
                ('ativo', models.BooleanField(default=True)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faltas', to='gestao.funcionario')),
            ],
        ),
        migrations.CreateModel(
            name='Orcamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_orcamento', models.DateField()),
                ('descricao', models.CharField(max_length=200)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orcamentos', to='gestao.cliente')),
            ],
        ),
    ]
