# Generated by Django 6.1 on 2026-08-21 21:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0002_funcionario_usuario_item_tipo_ponto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ponto',
            name='entrada',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='ponto',
            name='saida',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
