# Generated by Django 6.1 on 2026-08-22 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0004_auditlog_obra_item_obra_orcamento_obra_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='quantidade_minima',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
