# Generated by Django 6.1 on 2026-09-03 01:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0005_item_quantidade_minima'),
    ]

    operations = [
        migrations.CreateModel(
            name='Oportunidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('etapa', models.CharField(choices=[('novo', 'Novo contato'), ('visita', 'Visita técnica'), ('orcamento', 'Orçamento'), ('negociacao', 'Negociação'), ('aprovado', 'Aprovado'), ('perdido', 'Perdido')], default='novo', max_length=20)),
                ('origem', models.CharField(choices=[('indicacao', 'Indicação'), ('site', 'Site'), ('redes_sociais', 'Redes sociais'), ('prospeccao', 'Prospecção'), ('outro', 'Outro')], default='outro', max_length=20)),
                ('valor_estimado', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('data_previsao_fechamento', models.DateField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True)),
                ('motivo_perda', models.CharField(blank=True, max_length=250)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oportunidades', to='gestao.cliente')),
            ],
            options={
                'ordering': ['-atualizado_em', 'titulo'],
            },
        ),
    ]
