# Generated by Django 6.1 on 2026-09-03 01:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0006_oportunidade'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='oportunidade',
            name='data_proximo_contato',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='oportunidade',
            name='probabilidade_fechamento',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='oportunidade',
            name='responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oportunidades', to='gestao.funcionario'),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='oportunidade',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orcamento_convertido', to='gestao.oportunidade'),
        ),
        migrations.CreateModel(
            name='HistoricoOportunidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etapa_anterior', models.CharField(blank=True, max_length=20)),
                ('etapa_nova', models.CharField(max_length=20)),
                ('alterado_em', models.DateTimeField(auto_now_add=True)),
                ('alterado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('oportunidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='gestao.oportunidade')),
            ],
            options={
                'ordering': ['-alterado_em'],
            },
        ),
    ]
