# Generated by Django 6.1 on 2026-09-03 01:34

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import gestao.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0007_oportunidade_data_proximo_contato_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='obra',
            name='equipe',
            field=models.ManyToManyField(blank=True, related_name='obras_equipe', to='gestao.funcionario'),
        ),
        migrations.AddField(
            model_name='obra',
            name='percentual_concluido',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='obra',
            name='responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='obras_responsavel', to='gestao.funcionario'),
        ),
        migrations.CreateModel(
            name='DiarioObra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=django.utils.timezone.localdate)),
                ('resumo', models.TextField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diarios', to='gestao.obra')),
            ],
            options={
                'ordering': ['-data', '-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='FotoObra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='obras/fotos/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp']), gestao.models.validate_photo_size])),
                ('legenda', models.CharField(blank=True, max_length=200)),
                ('enviada_em', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='gestao.obra')),
            ],
        ),
        migrations.CreateModel(
            name='Ocorrencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('status', models.CharField(choices=[('aberta', 'Aberta'), ('em_tratamento', 'Em tratamento'), ('resolvida', 'Resolvida')], default='aberta', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('resolvido_em', models.DateTimeField(blank=True, null=True)),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocorrencias', to='gestao.obra')),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
    ]
