# Generated by Django 6.1 on 2026-09-03 01:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0008_obra_equipe_obra_percentual_concluido_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemOrcamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('material', 'Material'), ('mao_de_obra', 'Mão de obra'), ('equipamento', 'Equipamento'), ('servico', 'Serviço')], max_length=20)),
                ('descricao', models.CharField(max_length=200)),
                ('quantidade', models.DecimalField(decimal_places=3, max_digits=12)),
                ('custo_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('margem_percentual', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('orcamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='gestao.orcamento')),
            ],
        ),
    ]
