# Generated by Django 6.1 on 2026-09-03 01:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0009_itemorcamento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VersaoOrcamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField()),
                ('valor_anterior', models.DecimalField(decimal_places=2, max_digits=12)),
                ('valor_novo', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reajuste_percentual', models.DecimalField(decimal_places=2, max_digits=7)),
                ('motivo', models.CharField(max_length=250)),
                ('itens_snapshot', models.JSONField(default=list)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('orcamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versoes', to='gestao.orcamento')),
            ],
            options={
                'ordering': ['-numero'],
                'constraints': [models.UniqueConstraint(fields=('orcamento', 'numero'), name='unique_orcamento_versao')],
            },
        ),
    ]
